# Generated by Django 3.0.6 on 2020-05-09 00:51

import car.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=40, verbose_name='Make')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('RED', 'red'), ('WHITE', 'white'), ('BLUE', 'blue'), ('BLACK', 'black'), ('YELLOW', 'yellow')], default=car.models.Car.Colors['RED'], max_length=6)),
                ('model', models.CharField(max_length=40, verbose_name='Model')),
                ('size', models.CharField(choices=[('SUBCOMPACT', 'subcompact'), ('MID_SIZE', 'mid_size'), ('COMPACT', 'compact'), ('TWO_SEATER', 'twoseater'), ('FULL_SIZE', 'full_size'), ('STATIONWAGON_SMALL', 'stationwagon_small'), ('SUV_STANDARD', 'suv_standard')], default=car.models.Car.CarSize['FULL_SIZE'], max_length=18)),
                ('year', models.PositiveSmallIntegerField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maker', to='car.Make')),
            ],
        ),
    ]
