# Generated by Django 3.0.6 on 2020-05-09 04:00

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('RED', 'red'), ('WHITE', 'white'), ('BLUE', 'blue'), ('BLACK', 'black'), ('YELLOW', 'yellow'), ('SILVER', 'silver')], default=car.models.Car.Colors['RED'], max_length=6),
        ),
        migrations.AlterField(
            model_name='car',
            name='size',
            field=models.CharField(choices=[('SUBCOMPACT', 'Subcompact'), ('MID_SIZE', 'Mid Size'), ('COMPACT', 'Compact'), ('TWO_SEATER', 'Two Seater'), ('FULL_SIZE', 'Full Size'), ('STATIONWAGON_SMALL', 'Station Wagon - Small'), ('SUV_STANDARD', 'SUV Standard')], default=car.models.Car.CarSize['FULL_SIZE'], max_length=18),
        ),
    ]
