# Generated by Django 3.0.6 on 2020-05-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20200509_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='base_color',
        ),
    ]
